server:
  port: 8010

spring:
  redis:
    host: localhost
    password: 123456
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8000/jwks

jdbc:
  url: jdbc:h2:~/data/oauth2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  driverClassName: org.h2.Driver
  username: sa
  password:

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
    resource:
      token-info-uri: http://localhost:8000/oauth/check_token

#authorization:
#  client-type: jdbc
#  user-type: jdbc
#  token-type: jdbc

logging:
  level:
    org.springframework.security: trace
debug: true
